### ISSUE TITLE
Connecting Github account fails

### ISSUE THREAD

**Issue by gnidan** [madvas/ethlance#6]
I have an existing freelancer account on Ethlance, from before GH-connecting was implemented. After connecting my Github identity, the "Save User" button fails to provide any feedback, and I notice a JS console error:
```Uncaught TypeError: Cannot read property 'length' of null
    at r (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6703:24032)
    at Object.c [as encode] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6703:24748)
    at Object.l [as fromUtf8] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6700:17541)
    at i.f [as _inputFormatter] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6700:8923)
    at i.encode (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6700:13941)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6700:6039
    at Array.map (native)
    at d.encodeParams (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6700:6012)
    at s.toPayload (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6701:5246)
    at s.sendTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6701:6016)
r @ inpage.js:6703
c @ inpage.js:6703
l @ inpage.js:6700
f @ inpage.js:6700
i.encode @ inpage.js:6700
(anonymous) @ inpage.js:6700
d.encodeParams @ inpage.js:6700
s.toPayload @ inpage.js:6701
s.sendTransaction @ inpage.js:6701
s.execute @ inpage.js:6701
UR @ app.js?v=1.2.2:1381
CX.o @ app.js?v=1.2.2:1563
CX.I @ app.js?v=1.2.2:1563
q.h @ app.js?v=1.2.2:627
m8 @ app.js?v=1.2.2:2228
(anonymous) @ app.js?v=1.2.2:1539
nW @ app.js?v=1.2.2:1523
zW @ app.js?v=1.2.2:1525
g.Uh @ app.js?v=1.2.2:1536
FW @ app.js?v=1.2.2:1527
g.Xh @ app.js?v=1.2.2:1531
HW @ app.js?v=1.2.2:1528
(anonymous) @ app.js?v=1.2.2:1533
g.Sh @ app.js?v=1.2.2:1535
DW @ app.js?v=1.2.2:1526
(anonymous) @ app.js?v=1.2.2:1532
b.port1.onmessage @ app.js?v=1.2.2:1287
```

Using MetaMask

**Comment by madvas** [comment]
You're right, there was a bug with saving social networks under certain condition. I just deployed fix, please give it a try now

**Comment by gnidan** [comment]
I'm still having the same problem. Would this have anything to do with the apostrophe (`'`) in my last name, perhaps? Just a thought. Here's the error again:

```
Uncaught TypeError: Cannot read property 'length' of null
    at r (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6708:24032)
    at Object.c [as encode] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6708:24748)
    at Object.l [as fromUtf8] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6705:17541)
    at i.f [as _inputFormatter] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6705:8923)
    at i.encode (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6705:13941)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6705:6039
    at Array.map (native)
    at d.encodeParams (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6705:6012)
    at s.toPayload (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6706:5246)
    at s.sendTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6706:6016)
```

(Seems I missed the first line above)

**Comment by madvas** [comment]
hmm, pretty sure it's not apostrophe. I guess your browser just cached page somehow (even though it shouldn't), please try to refresh page several times just in case

**Comment by gnidan** [comment]
I've done "Empty Cache and Hard Reload" and also cleared all application data with Chrome. No dice.

**Comment by madvas** [comment]
Damn, this is so weird, since the error is exactly what I've fixed. Just to make sure for one last time. When you open devtools. Do you see version `1.2.5` in `./js/compiled/app.js?v=1.2.5`?

![image](https://cloud.githubusercontent.com/assets/3857155/23179604/c104deac-f86e-11e6-805d-cbdc87b7a81d.png)

**Comment by gnidan** [comment]
<img width="1343" alt="screen shot 2017-02-21 at 13 51 50" src="https://cloud.githubusercontent.com/assets/151065/23179742/f182c9c2-f83c-11e6-8ec4-60554c844f02.png">

It appears so!

**Comment by madvas** [comment]
Ok, I'm pretty sure I fixed it now. Please give it a shot again. Make sure you see `v=1.2.6` first. Thank you very much for your assistance

**Comment by gnidan** [comment]
It works! Thanks a bunch @madvas :)
